
default: &default
  adapter: postgresql
  encoding: unicode

  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  username: postgres
  password: vmurtag33
  database: Ieat_development

test:
  <<: *default
  database: Ieat_test

production:
  <<: *default
  database: Ieat_production
  username: Ieat
  password: <%= ENV['IEAT_DATABASE_PASSWORD'] %>
